name:CI/CD Pipeline

on:
  push:
    branches:
      -main
jobs:
  build:
    runs-on:ubuntu-latest

    steps:
      -name:Checkout code
       uses:actions/checkout@v2

       -name:Install dependencies
       run:npm install

       -name:Build Docker image
       run: |
         docker build -t C:\Program Files\Docker\Docker\my_image:latest
         docker push
     C:\Program Files\Docker\Docker\my_image:latest
       -name:Terraform Init
       uses:
      hashicorp/setup-terraform@v1
        with:
          terraform_version:0.15.0

          -name:Terraform Plan
          run:terraform plan

          -name:Terraform Apply
          run:terraform apply
      -auto-approve

          
